language: php

dist: trusty
sudo: false

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

git:
  depth: 1

services:
  - redis-server

before_install:
  - export PHP_MAJOR="$(`phpenv which php` -r 'echo phpversion();' | cut -d '.' -f 1)"
  - export PHP_MINOR="$(`phpenv which php` -r 'echo phpversion();' | cut -d '.' -f 2)"
  - echo $PHP_MAJOR
  - echo $PHP_MINOR

install:
  - cd $TRAVIS_BUILD_DIR
  # 更新扩展
  - phpenv config-add tests/ci.ini
  # 安装项目
  - composer self-update
  - cd $TRAVIS_BUILD_DIR
  - composer install --prefer-dist --optimize-autoloader

script:
  - cd $TRAVIS_BUILD_DIR
  - ./vendor/bin/phpunit