language: php

dist: trusty
sudo: false

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

git:
  depth: 1

services:
  - redis-server

before_install:
  - export PHP_MAJOR="$(`phpenv which php` -r 'echo phpversion();' | cut -d '.' -f 1)"
  - export PHP_MINOR="$(`phpenv which php` -r 'echo phpversion();' | cut -d '.' -f 2)"
  - echo $PHP_MAJOR
  - echo $PHP_MINOR

install:
  - cd $TRAVIS_BUILD_DIR
  # 更新扩展
  - wget https://github.com/redis/hiredis/archive/v0.13.3.tar.gz -O hiredis.tar.gz && mkdir -p hiredis && tar -xf hiredis.tar.gz -C hiredis --strip-components=1 && cd hiredis && sudo make -j$(nproc) && sudo make install && sudo ldconfig && cd ..
  - bash tests/swoole.install.sh
  - phpenv config-rm xdebug.ini
  - phpenv config-add tests/ci.ini
  - cp -rf $TRAVIS_BUILD_DIR/tests/.env.example $TRAVIS_BUILD_DIR/tests/.env
  # 安装项目
  - composer self-update
  - cd $TRAVIS_BUILD_DIR
  - composer install --prefer-dist --optimize-autoloader

script:
  - cd $TRAVIS_BUILD_DIR
  - ./vendor/bin/phpunit